fail_fast: true
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        args: ["--ignore=F401"]
        additional_dependencies: ["flake8-bugbear==21.4.3"]
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'  # Use a specific version if needed
    hooks:
      - id: pylint
        args: ["--disable=C0114,E0401,E1101,R0903"]

