name: Deploy Odoo on Server
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install flake8
        run: python -m pip install flake8
      - name: Check Python code with flake8
        run: |
          flake8 --ignore=F401,W292,E501,W293,W291,W391,F811,E303
        continue-on-error: false
      - name: Install Bandit
        run: python -m pip install bandit
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
   
  pull-request:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging' && contains(github.event.head_commit.message, 'PR')
    steps:
      - name: Check commit message for 'PR'
        run: |
          if [[ $(git log --format=%B -n 1 $GITHUB_SHA) =~ PR ]]; then
            exit 0
          else
            exit 1
          fi
      - name: Create pull request
        if: success()
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
